version: '3.8'
services:
  timescaledb:
    build:
      context: timescaledb
    hostname: timescaledb
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=PsWDgxZb
    networks:
      - net-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    build:
      context: migrations
    networks:
      - net-net
    env_file:
      - .env
    depends_on:
      timescaledb:
        condition: service_healthy
    entrypoint: >
      sh -c "
        until pg_isready -h timescaledb -p 5432 -U postgres; do
          echo 'Waiting for database...'
          sleep 1
        done &&
        echo 'Database is ready. Running migrations...' &&
        sqlx database create --database-url $$DATABASE_URL &&
        sqlx migrate run --database-url $$DATABASE_URL
      "

networks:
  net-net:
    driver: bridge
    name: net-net
