version: '3.8'

services:
  timescaledb:
    build:
      context: timescaledb
    hostname: timescaledb
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=PsWDgxZb
    networks:
      - net-net
  
  timescaledb-buffer:
    build:
      context: timescaledb
    hostname: timescaledb-buffer
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=PsWDgxZb
    networks:
      - net-net

networks:
  net-net:
    driver: bridge
    name: net-net
