[timescaledb_connection_url]
url = "postgres://postgres:PsWDgxZb@localhost:5433"

[timescaledb_buffer_connection_url]
url = "postgres://postgres:PsWDgxZb@localhost:5434"

[max_connection_size]
size = "10"

[server]
host_name = "net-updater"
port = "5456"
addr = "127.0.0.1"
