[connection_url]
url = "postgres://postgres:PsWDgxZb@localhost:5433/?sslmode=require&sslcert=docker/.ssl/client.crt&sslkey=docker/.ssl/client.key"

[max_connection_size]
size = "10"

[server_address]
address = "127.0.0.1:5455"

[fusion_auth_server_addres]
addr = "http://localhost:9011"

[fusion_auth_api_key]
key = "gw_awXW6h11DZ7ncwyim23-wQ76IAsM947L5p9Wb7yYOR0Erh_yQKCD4"